version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:8000

    depends_on:
      - db
      - redis
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: laravelambassador
      MYSQL_USER: armenat
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: armenat
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  redis:
    image: redis
    ports:
      - 6379:6379
